### ISSUE TITLE
Perf opportunities: Ractor the Rippers

### ISSUE THREAD

**Issue by schneems** [zombocom/dead_end#115]
I think there's an opportunity to parallelize the code search somewhat. 

The most expensive part of code search is calling `Ripper.parse` to see if there is a syntax error. We do this in two places: 

- 1) To check if the whole frontier contains all errors
- 2) To check an individual block if it is valid or not 

Previously I got a massive speed boost by minimizing calls to the first one by checking if the frontier had accepted any new "invalid" blocks or not. Because we must check every block for this strategy we cannot minimize number 2 but it might be possible to parse multiple blocks at once.

## Strategy

In the `expand` phase of the code search, don't pop one block, pop all of them for that given indentation. We can then expand each block and check it in a factor in parallel before inserting them all back onto the frontier. 

## Considerations

Only code that is frozen or copied can be passed to ractors. We currently mutate and share `code_lines` all over the place. We mutate to mark a code line as "invisible". This happens when it is part of a block that has been determined to be "valid".

I think we could move the mutation out of CodeLine and into a mask object, then later use Array#intersection to handle the case of recording modifications. Alternatively, we could expand blocks in the main thread and only use the ractors to check for syntax errors in the blocks. For that case we could send over frozen strings and it could return a boolean yes/no for parsing or not.

## Possible speedup

We're limited by how many blocks we can produce on a given expansion phase. Ideally, N cores would check N blocks on every execution but there won't always be exactly N blocks.

Currently, we are spending 12% of our time checking if blocks are valid:

![](https://www.dropbox.com/s/b845j2plpb11ep5/Screen%20Shot%202021-11-12%20at%203.51.37%20PM.png?raw=1)

Assuming we had perfect utilization and assuming zero scheduling cost we could reduce it (at best) by %-time divided by N. For a 16 core system it could take 12% / 16 #=> 0.75%. Which would yield a savings of 11.25%. For a run that takes 0.12 seconds, it would bring the time down to 0.1065 seconds.

## Problems

As I'm writing this up, it looks like ripper is not marked as "ractor safe" 

```
$ cat -n scratch.rb
     1	require 'ripper'
     2
     3	source = "puts 'lol'".freeze
     4
     5	def no_ractor(source)
     6	  16.times.map do
     7	    ripper = Ripper.new(source)
     8	    ripper.parse
     9	    ripper.error?
    10	  end
    11	end
    12
    13	def ractor(source)
    14	  ractors = 16.times.map do
    15	    Ractor.new(source) do |source|
    16	      ripper = Ripper.new(source)
    17	      ripper.parse
    18	      !!ripper.error?
    19	    end
    20	  end
    21
    22	  ractors.map(&:take)
    23	end
    24
    25	no_ractor(source)
    26	ractor(source)
⛄️ 3.0.2 🚀 /tmp
$ ruby scratch.rb
<internal:ractor>:267: warning: Ractor is experimental, and the behavior may change in future versions of Ruby! Also there are many implementation issues.
#<Thread:0x00007f81db8d3da8 run> terminated with exception (report_on_exception is true):
#<Thread:0x00007f81db8d3740 run> terminated with exception (report_on_exception is true):
#<Thread:0x00007f81db8d3b78 run> terminated with exception (report_on_exception is true):
scratch.rb:16:in `initialize'scratch.rb:16:in `initialize'scratch.rb:16:in `initialize': : : ractor unsafe method called from not main ractorractor unsafe method called from not main ractorractor unsafe method called from not main ractor#<Thread:0x00007f81db8d35d8 run> terminated with exception (report_on_exception is true):
 ( (Ractor::UnsafeErrorRactor::UnsafeError (#<Thread:0x00007f81db8d33a8 run> terminated with exception (report_on_exception is true):
))Ractor::UnsafeError
scratch.rb:16:in `initialize')
scratch.rb:16:in `initialize': ractor unsafe method called from not main ractor:
 (Ractor::UnsafeError)#<Thread:0x00007f81db8d3178 run> terminated with exception (report_on_exception is true):
	from scratch.rb:16:in `new'
ractor unsafe method called from not main ractor
	from scratch.rb:16:in `block (2 levels) in ractor'
	from scratch.rb:16:in `new'
	from scratch.rb:16:in `new'
	from scratch.rb:16:in `new'
 (	from scratch.rb:16:in `block (2 levels) in ractor'
```

**Comment by schneems** [comment]
I wrote this up as an exercise in documentation because I didn't want to work on it now, however I couldn't stop thinking about it.

In the process I've proved: 
- It's not possible due to current ractor limitations
- The potential speedup is at best 11% which is something, but not massive
