### ISSUE TITLE
Extending the idea to _stack level too deep_

### ISSUE THREAD

**Issue by BuonOmo** [zombocom/dead_end#133]
Hi @schneems 

I recently got tired of the message we get for _stack level too deep_ (just a long backtrace). There is an ellipsis already making it more readable.

On my local stack I've added a more concise message:

```
Most frequent loop (3374 times):                 <----- the addition
/Users/u.buonomo/Dev/loop.rb:10:in `c'
/Users/u.buonomo/Dev/loop.rb:6:in `b'
/Users/u.buonomo/Dev/loop.rb:2:in `a'

Traceback (most recent call last):               <----- the original message
        11911: from t.rb:1:in `<main>'
        11910: from /Users/u.buonomo/.ruby/stack_level_too_deep.rb:54:in `require'
        11909: from /Users/u.buonomo/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        11908: from /Users/u.buonomo/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        11907: from /Users/u.buonomo/Dev/loop.rb:14:in `<top (required)>'
        11906: from /Users/u.buonomo/Dev/loop.rb:2:in `a'
        11905: from /Users/u.buonomo/Dev/loop.rb:6:in `b'
        11904: from /Users/u.buonomo/Dev/loop.rb:10:in `c'
         ... 11899 levels...
            4: from /Users/u.buonomo/Dev/loop.rb:10:in `c'
            3: from /Users/u.buonomo/Dev/loop.rb:2:in `a'
            2: from /Users/u.buonomo/Dev/loop.rb:6:in `b'
            1: from /Users/u.buonomo/Dev/loop.rb:10:in `c'
/Users/u.buonomo/Dev/loop.rb:2:in `a': stack level too deep (SystemStackError)
```

Not sure if it is the best place to talk about such an idea. But I figured it is also a matter of having nicer error messages for ruby.

Of course I'm not saying this should be part of dead_end (I've called this thing `StackLoop` for now).

I'd be glad to have your opinion's on such an idea, and maybe other members of the community to see if there is somehow an interest for such an improvement

Cheers

**Comment by schneems** [comment]
Ahh, gotcha. Yeah. I'm open to putting this or something like it in the zombocom namespace. What would you need from me? I'm not totally sure what permissions others have over here. 

Looking at the code

- I would say that for `dead_end` monkeypatching `require` is a not great interface. It causes some confusion like https://github.com/zombocom/dead_end/issues/124. But looking into ruby/ruby I can't easily see where that exception is defined. I see it referenced in https://github.com/ruby/ruby/blob/9e0a91d0640600f2dfd7fc1d5fae6667019c9ca5/error.c#L2822. It's not a dealbreaker, just mentioning that experience.
- A `Set` is actually a `Hash` under the hood, you might be able to combine those two (or maybe not, just mentioning as it was surprising to me when I learned that). 
- If it's that relatively simple it might be able to be patched into Ruby directly, but it would be good to prove out with a gem first to have some room to play and get feedback.
- I took a stab at monkeypatching `SystemStackError` and it does look possible:
```
class SystemStackError
  def message
    puts "lol"
    super
  end
end

def foo
  foo
end

foo
```

gives me:

```
scratch.rb:9:in `foo': stack level too deep (SystemStackError)
	from scratch.rb:9:in `foo'
	from scratch.rb:9:in `foo'
	from scratch.rb:9:in `foo'
	from scratch.rb:9:in `foo'
	from scratch.rb:9:in `foo'
	from scratch.rb:9:in `foo'
	from scratch.rb:9:in `foo'
	from scratch.rb:9:in `foo'
	 ... 10908 levels...
	from scratch.rb:9:in `foo'
	from scratch.rb:9:in `foo'
	from scratch.rb:9:in `foo'
	from scratch.rb:12:in `<main>'
```

Also it does compress the stacktrace a little already (though not as nice as you're mentioning. It might be worth looking into where that message comes from (perhaps search "levels..." on ruby/ruby) maybe there's already a place for logic to be extended, maybe a `blame` on that code will give you some context and extra details of concerns or other attempts others have made.

It looks like if you make the stack trace longer it cuts it off after a point:

```
class SystemStackError
  def message
    puts "lol"
    super
  end
end

def blerg 
  foo
end

def baz
  blerg
end

def bar
  baz
end

def foo
  bar 
end

foo
```

```
$ ruby scratch.rb
lol
scratch.rb:21:in `foo': stack level too deep (SystemStackError)
	from scratch.rb:9:in `blerg'
	from scratch.rb:13:in `baz'
	from scratch.rb:17:in `bar'
	from scratch.rb:21:in `foo'
	from scratch.rb:9:in `blerg'
	from scratch.rb:13:in `baz'
	from scratch.rb:17:in `bar'
	from scratch.rb:21:in `foo'
	 ... 11901 levels...
	from scratch.rb:13:in `baz'
	from scratch.rb:17:in `bar'
	from scratch.rb:21:in `foo'
```

**Comment by BuonOmo** [comment]
> Ahh, gotcha. Yeah. I'm open to putting this or something like it in the zombocom namespace. What would you need from me? I'm not totally sure what permissions others have over here.

Well I could [create the repository](https://github.com/zombocom/stack_loop), [push a commit to the main branch of an existing repository](https://github.com/zombocom/super_duper/commit/22374d547dde1deb2cf41d8f741a10c214d06b50) and push force to that same commit after seing I made a typo. So the scope is pretty wide!

> I can't easily see where the error is referenced / perhaps search "levels"

It is the `rb_eSysStackError`, and I've seen some work on it [in this commit](https://github.com/ruby/ruby/pull/3047/files), it seems like what has been done is just reducing the stack as you've shown. I think there is still some room for improvement since most conversations were more focused on the overall backtrace size/the order of the backtrace rather than on this specific error ([conversation here](https://bugs.ruby-lang.org/issues/8661#note-33))

> If it's that relatively simple it might be able to be patched into Ruby directly, but it would be good to prove out with a gem first to have some room to play and get feedback.

Yeah I've already seen where the patch could be, but feedback will be mandatory on that since I'm far from being sure which is the best way of showing loops (or recurring stack calls)


Anyway I've started the thing, I think I'll sleep on it a few days, improve, loop and introduce that to project when I'll have a clearer idea of what the message should be.

Thanks for your time 🙂

To all, any feedback would be really appreciated! Open an issue [here](https://github.com/zombocom/stack_loop/issues) to discuss 👀

**Comment by BuonOmo** [comment]
>  It's also one of the reasons why I wanted to get some extra people with commit on some of these projects so there's not a single blocker for moving things forwards when I occasionally drop the ball.

Makes sense, I'm not actively looking at issues on derailed or here since I already have the rgeo codebase to look after. However, if something feels important and you don't have the time feel free to ping me :)
