### ISSUE TITLE
cannot load such file -- celluloid/current (LoadError)

### ISSUE THREAD

**Issue by warunacds** [zombocom/dead_end#61]
Getting this error after dead_end updated to 1.1.6

```
Traceback (most recent call last):
20: from bin/rails:9:in `<main>'
19: from bin/rails:9:in `require'
18: from /Users/waruna/.gem/ruby/2.7.0/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
17: from /Users/waruna/.gem/ruby/2.7.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
16: from /Users/waruna/.gem/ruby/2.7.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:85:in `server'
15: from /Users/waruna/.gem/ruby/2.7.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:85:in `tap'
14: from /Users/waruna/.gem/ruby/2.7.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:88:in `block in server'
13: from /Users/waruna/.gem/ruby/2.7.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:88:in `require'
12: from /Users/waruna/Project/example-server/config/application.rb:7:in `<top (required)>'
11: from /Users/waruna/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler.rb:174:in `require'
10: from /Users/waruna/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
 9: from /Users/waruna/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
 8: from /Users/waruna/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
 7: from /Users/waruna/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
 6: from /Users/waruna/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
 5: from /Users/waruna/.gem/ruby/2.7.0/gems/dead_end-1.1.6/lib/dead_end/auto.rb:21:in `require'
 4: from /Users/waruna/.gem/ruby/2.7.0/gems/dead_end-1.1.6/lib/dead_end/auto.rb:21:in `require'
 3: from /Users/waruna/.gem/ruby/2.7.0/gems/sidetiq-0.7.2/lib/sidetiq.rb:10:in `<top (required)>'
 2: from /Users/waruna/.gem/ruby/2.7.0/gems/dead_end-1.1.6/lib/dead_end/auto.rb:50:in `require'
 1: from /Users/waruna/.gem/ruby/2.7.0/gems/dead_end-1.1.6/lib/dead_end/auto.rb:21:in `require'
/Users/waruna/.gem/ruby/2.7.0/gems/dead_end-1.1.6/lib/dead_end/auto.rb:21:in `require': cannot load such file -- celluloid/current (LoadError)
```

**Comment by warunacds** [comment]
Further investigation into this issue, reveals that this was causing due deprecated library 'sidetiq'. After replacing that issue went away. Therefore I'm going to close this. Thanks for looking into it.
