### ISSUE TITLE
Didn't catch syntax error

### ISSUE THREAD

**Issue by schneems** [zombocom/dead_end#62]
```
# frozen_string_literal: true

module Cutlass
  class PackBuild
    private; attr_reader :app_dir, :config, :builder, :image_name, :buildpacks; :env_arguments public

    def initialize(app_dir:, image_name: default_image_name, buildpacks: [], config: {}, builder: )
      @app_dir = app_dir
      @builder = builder
      @image_name = image_name
      @env_arguments = config.map {|key, value| "--env #{key}=#{value}" }.join(" ")

      @buildpacks = buildpacks.map do |buildpack|
        if buildpack.respond_to?(:name)
          buildpack.name
        else
          buildpack
        end
      end
    end

    def call
      puts pack_command if ENV["CUTLASS_DEBUG"] || ENV["DEBUG"]
      call_pack
    end

    private def call_pack
      stdout, stderr, status = Open3.capture3(pack_command)

      if pack_status == 0
        image = Docker::Image.get(image_name)
      else
        image = nil
        if exception_on_failure
          raise "Pack exited with status code #{pack_status}, indicating an error and failed build!\nstdout: #{pack_stdout}\nstderr: #{pack_stderr}"
        end
      end
    end

    def pack_command
      "pack build #{image_name} --path #{app_dir} -B #{builder} --buildpack #{buildpacks.join(',')} #{env_arguments}"
    end

    def default_image_name
      "cutlass_image_#{SecureRandom.hex(10)}"
    end
  end

  RSpec.describe Cutlass::LocalBuildpack do
    it "" do
    end

    it "builds images and tears them down" do
      Dir.mktmpdir do |dir|
        name = SecureRandom.hex(10)
        dir = Pathname(dir)
        dir.join("package.toml").write(<<~EOM)
          [buildpack]
          uri = "."
        EOM
        dir.join("buildpack.toml").write(<<~EOM)
          [buildpack]
          id = "cutlass/supreme_#{name}"
          version = "0.0.1"

          [[stacks]]
          id = "io.buildpacks.stacks.bionic"
        EOM

        diff = DockerDiff.new
        local_buildpack = LocalBuildpack.new(directory: dir)
        local_buildpack.call
        expect(diff.call.changed?).to be_truthy
        local_buildpack.teardown if local_buildpack

        expect(diff.call.changed?).to be_falsey
      end
    end
  end
end
```

Ruby 3.0.1:

```
$ CUTLASS_CHECK_DOCKER=1 be rspec spec/unit/

An error occurred while loading ./spec/unit/local_buildpack_spec.rb.
Failure/Error: dead_end_original_load(file)

SyntaxError:
  /Users/rschneeman/Documents/projects/work/cutlass/spec/unit/local_buildpack_spec.rb:5: syntax error, unexpected local variable or method, expecting `end'
  ...ildpacks; :env_arguments public
  ...                         ^~~~~~
# /Users/rschneeman/.gem/ruby/3.0.1/gems/dead_end-1.1.6/lib/dead_end/auto.rb:15:in `load'
# /Users/rschneeman/.gem/ruby/3.0.1/gems/dead_end-1.1.6/lib/dead_end/auto.rb:15:in `load'
# /Users/rschneeman/.gem/ruby/3.0.1/gems/dead_end-1.1.6/lib/dead_end/auto.rb:44:in `load'
```

**Comment by schneems** [comment]
The reason dead end doesn't fire is because this error message:

```
/Users/rschneeman/Documents/projects/work/cutlass/spec/unit/local_buildpack_spec.rb:5: syntax error, unexpected local variable or method, expecting `end'
...ildpacks; :env_arguments public
...                         ^~~~~~
```

Does not contain the value `end-of-input`. Which we expect:

https://github.com/zombocom/dead_end/blob/9214142f24455ec48e9bf384df626efa5977f8fc/lib/dead_end/internals.rb#L20

I don't know why this error is different than other errors. It's also notable that it actually points out the location of the syntax error via the location `^~~~~~` already (though it's not very readable IMHO).

I'm guessing this is some kind of a special case. Originally I thought it might be due to a change in Ruby with 3.x but it looks like it's present in 2.7 and 2.6 so at least it's consistent. 

- 2.7

```

SyntaxError:
  /Users/rschneeman/Documents/projects/work/cutlass/spec/unit/local_buildpack_spec.rb:5: syntax error, unexpected local variable or method, expecting `end'
  ...ildpacks; :env_arguments public
  ...                         ^~~~~~
```

- 2.6
```
SyntaxError:
  /Users/rschneeman/Documents/projects/work/cutlass/spec/unit/local_buildpack_spec.rb:5: syntax error, unexpected tIDENTIFIER, expecting end
  ...ildpacks; :env_arguments public
  ...                         ^~~~~~
```

That last `tIDENTIFIER` in 2.6 makes me think this syntax error might be coming from the lexer instead of a "normal" location

**Comment by schneems** [comment]
I think this behavior was introduced in Ruby in https://github.com/ruby/ruby/commit/70af8d3c9ca2a46ef1f364783125a747d9426b2b. It's unclear from that diff how exactly that `^~~~` value gets added though. I'm looking at blame from test_parse.rb and it's helping a bit (but still a very incomplete picture) https://github.com/ruby/ruby/blame/a33948f40a64d038ef848783dcfb33d801bc7018/test/ruby/test_parse.rb

**Comment by schneems** [comment]
Also it's worth mentioning it looks like this is where the `^~~` message gets formatted https://github.com/ruby/ruby/commit/a13636e756662e563e4c4dc802c6fa21cb6d7b52

**Comment by schneems** [comment]
This is a weird case because it doesn't fit into any of the neat buckets I've made for various failure cases. Even the message from Ruby isn't quite right. It's not missing an end, it's missing a semicolon. Even though it says "missing an end" it cannot be fixed by adding an end to the code. I'm wondering if it's possible that's considered a "bug" in Ruby as the message is incorrect.

**Comment by schneems** [comment]
Same cause as https://github.com/zombocom/dead_end/issues/65
