### ISSUE TITLE
Room for improvement

### ISSUE THREAD

**Issue by schneems** [zombocom/dead_end#72]
```
# frozen_string_literal: true

require_relative "../spec_helper"

module Omgcnb
  RSpec.describe BuildpacksFromDir do
    it "does not error" do
      dir = node_buildpack_dir
      buildpacks = BuildpacksFromDir.new(dir: dir).buildpacks
      expect(buildpacks.count).to eq(0)
    end
end
```

Gives me:

```
$ rspec spec/unit/buildpacks_from_dir_spec.rb
Run `$ dead_end /Users/rschneeman/Documents/projects/omgcnb/spec/unit/buildpacks_from_dir_spec.rb` for more options

DeadEnd: Missing `end` detected

This code has a missing `end`. Ensure that all
syntax keywords (`def`, `do`, etc.) have a matching `end`.

file: /Users/rschneeman/Documents/projects/omgcnb/spec/unit/buildpacks_from_dir_spec.rb
simplified:

      3  require_relative "../spec_helper"
    ❯ 5  module Omgcnb



Run `$ dead_end /Users/rschneeman/Documents/projects/omgcnb/spec/unit/buildpacks_from_dir_spec.rb` for more options

DeadEnd: Missing `end` detected

This code has a missing `end`. Ensure that all
syntax keywords (`def`, `do`, etc.) have a matching `end`.

file: /Users/rschneeman/Documents/projects/omgcnb/spec/unit/buildpacks_from_dir_spec.rb
simplified:

      3  require_relative "../spec_helper"
    ❯ 5  module Omgcnb




An error occurred while loading ./spec/unit/buildpacks_from_dir_spec.rb.
Failure/Error: dead_end_original_load(file)

SyntaxError:
  /Users/rschneeman/Documents/projects/omgcnb/spec/unit/buildpacks_from_dir_spec.rb:12: syntax error, unexpected end-of-input, expecting `end'
# /Users/rschneeman/.gem/ruby/3.0.2/gems/dead_end-1.1.7/lib/dead_end/auto.rb:15:in `load'
# /Users/rschneeman/.gem/ruby/3.0.2/gems/dead_end-1.1.7/lib/dead_end/auto.rb:15:in `load'
# /Users/rschneeman/.gem/ruby/3.0.2/gems/dead_end-1.1.7/lib/dead_end/auto.rb:44:in `load'
No examples found.

Finished in 0.00004 seconds (files took 0.47282 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by schneems** [comment]
Closed by #73

```
$ gem install dead_end
Fetching dead_end-1.2.0.gem
Successfully installed dead_end-1.2.0
Parsing documentation for dead_end-1.2.0
Installing ri documentation for dead_end-1.2.0
Done installing documentation for dead_end after 0 seconds
1 gem installed
⛄️ 3.0.2 🚀 /Users/rschneeman/Documents/projects/dead_end (schneems/trailing-leading-dot)
$ dead_end /tmp/scratch.rb

DeadEnd: Missing `end` detected

This code has a missing `end`. Ensure that all
syntax keywords (`def`, `do`, etc.) have a matching `end`.

file: /tmp/scratch.rb
simplified:

       3  require_relative "../spec_helper"
    ❯  5  module Omgcnb
    ❯  6    RSpec.describe BuildpacksFromDir do
    ❯ 12  end
```
